CREATE OR ALTER VIEW View_Columns AS
SELECT C.TABLE_SCHEMA
     , C.TABLE_NAME
     , C.COLUMN_NAME
     , C.DATA_TYPE
     , C.CHARACTER_MAXIMUM_LENGTH
     , C.NUMERIC_PRECISION
     , C.NUMERIC_SCALE
    FROM INFORMATION_SCHEMA.COLUMNS C
        JOIN
    INFORMATION_SCHEMA.TABLES       T
    ON C.TABLE_NAME = T.TABLE_NAME
    WHERE T.TABLE_TYPE = 'BASE TABLE'
      AND (C.TABLE_SCHEMA NOT LIKE 'sys%'
               AND C.TABLE_SCHEMA NOT LIKE '%_db%'
        OR C.TABLE_SCHEMA = 'dbo')
GO