CREATE OR ALTER VIEW View_Schemas AS
SELECT SCHEMA_NAME
    FROM INFORMATION_SCHEMA.SCHEMATA
    WHERE SCHEMA_NAME NOT LIKE 'sys%'
        AND SCHEMA_NAME NOT LIKE 'db_%'
        AND SCHEMA_NAME NOT LIKE 'INFORMATION_SCHEMA'
        AND SCHEMA_NAME != 'guest'
       OR SCHEMA_NAME = 'dbo'
GO