CREATE OR ALTER VIEW View_Tables AS
SELECT TABLE_SCHEMA, TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA')
        AND TABLE_SCHEMA NOT LIKE 'db_%'
       OR TABLE_SCHEMA = 'dbo'
        AND TABLE_TYPE = 'BASE TABLE'
GO